# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: VisionIndex
email: visindx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog-posts, reviews, speculations, and code projects
  on Software engineering, Computer vision, Robotics
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  pamirghimire
youtube_username: balabala

# Build settings
markdown: kramdown


#--for-github--DO--NOT--CHANGE--:
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
#--for-github--DO--NOT--CHANGE--:
theme: jekyll-theme-cayman